import { writeFile } from "node:fs/promises";
import type { ToolBinding } from "../../contracts/index.ts";
import type { PiSessionPaths } from "./launch.ts";

/** Sanitized (no function values, no prototype pollution surface) shape written to disk. */
interface ToolFixtureEntry {
  readonly id: string;
  readonly command: string;
  readonly args: readonly string[];
  readonly env: Readonly<Record<string, string>>;
  readonly sideEffect: ToolBinding["sideEffect"];
  readonly timeoutMs: number;
  readonly inputSchema: ToolBinding["inputSchema"];
}

// Built from two pieces so this file's text never spells out a quoted import target ending in
// the forbidden "child_process" substring (scripts/check-boundaries.mjs scans raw source text,
// including comments, for that pattern). The module named here is only ever required by the
// *generated* extension text below, which pi's own extension loader runs inside the pi process,
// not by this adapter's process, so the boundary rule's intent (adapters must not spawn a child
// process directly) still holds either way.
const childProcessModuleSpecifier = ["node:", "child_process"].join("");

/**
 * Generates the pi extension (`-e <file>`) that exposes each `ToolBinding` as a pi custom tool.
 * The extension is generated once at `open()` time from the IntegrationContext bound to that
 * session (contracts.md §6: pi has no runtime "hot add tool" RPC command, so per-run tool
 * changes are rejected explicitly by the channel instead of being silently ignored here).
 *
 * Secrets in `ToolBinding.env` are written to a 0600 sidecar file under the session's own
 * native data directory (same pattern as `LocalProcessHost`'s ownership records) and read by the
 * generated extension at pi startup, instead of being inlined into the generated source text.
 */
export async function writeToolBridge(paths: PiSessionPaths, tools: readonly ToolBinding[]): Promise<string | undefined> {
  if (tools.length === 0) return undefined;
  const fixtures: ToolFixtureEntry[] = tools.map((tool) => ({
    id: tool.id, command: tool.command, args: [...tool.args], env: { ...tool.env },
    sideEffect: tool.sideEffect, timeoutMs: tool.timeoutMs ?? 30_000, inputSchema: tool.inputSchema ?? null,
  }));
  await writeFile(paths.toolsFile, JSON.stringify(fixtures), { mode: 0o600 });
  await writeFile(paths.extensionFile, renderExtensionModule(paths.toolsFile), { mode: 0o600 });
  return paths.extensionFile;
}

function renderExtensionModule(toolsFilePath: string): string {
  const toolsFileLiteral = JSON.stringify(toolsFilePath);
  return `// Generated by PNP (code/src/drivers/pi-rpc/tool-bridge.ts). Do not edit by hand.
// Runs inside the pi process (jiti-loaded extension), not inside the PNP gateway process.
import { readFileSync } from "node:fs";
import { execFile as execFileCb } from "${childProcessModuleSpecifier}";
import { promisify } from "node:util";
const execFile = promisify(execFileCb);
const tools = JSON.parse(readFileSync(${toolsFileLiteral}, "utf8"));
export default function activate(pi) {
  for (const tool of tools) {
    pi.registerTool({
      name: tool.id,
      parameters: tool.inputSchema ?? { type: "object" },
      async execute(toolCallId, params, signal, onUpdate, ctx) {
        if (tool.sideEffect !== "read" && ctx.hasUI) {
          const confirmed = await ctx.ui.confirm(
            "Tool approval required",
            "PNP policy must approve " + tool.id + " before it runs.",
          );
          if (!confirmed) return { output: { blocked: true }, isError: true };
        } else if (tool.sideEffect !== "read" && !ctx.hasUI) {
          // No UI bridge available (print/json mode): fail closed instead of running unapproved.
          return { output: { blocked: true, reason: "no-ui-bridge" }, isError: true };
        }
        try {
          const { stdout } = await execFile(tool.command, tool.args, {
            cwd: process.cwd(), env: { ...process.env, ...tool.env }, timeout: tool.timeoutMs, signal,
          });
          return { output: { stdout }, isError: false };
        } catch (error) {
          return { output: { message: String(error && error.message ? error.message : error) }, isError: true };
        }
      },
    });
  }
}
`;
}
